#!/bin/bash -euo pipefail

vault=$1
shift
secret_id=$1
shift

cat <<END | op inject $@
{
  "Version": 1,
  "AccessKeyId": "{{ op://${vault}/${secret_id}/access key id }}",
  "SecretAccessKey": "{{ op://${vault}/${secret_id}/secret access key }}"
}
END
