# Table of Contents
# 00 projects
# 01 unpackaged software
# 02 zsh plugins
# 03 vim plugins


# 00 projects


# 01 unpackaged software
[".local/share/git-fuzzy"]
  type = "git-repo"
  url = "https://github.com/bigH/git-fuzzy"
  refreshPeriod = "168h"
{{ if .server }}
[".bin/tailscale-nginx-auth"]
  type = "file"
  url = "https://github.com/indirect/dotfiles/releases/download/nginx-auth-1-4f6fa3d6/nginx-auth"
  executable = true
{{ end }}

# 02 zsh plugins
[".zsh/znap/zsh-snap"]
  type = "archive"
  url = "https://github.com/marlonrichert/zsh-snap/archive/refs/heads/main.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

# 03 vim plugins
[".vim/autoload/plug.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
  refreshPeriod = "168h"
[".vim/colors/made-of-code.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/indirect/dotfiles/main/dot_vim/colors/made-of-code.vim"
  refreshPeriod = "168h"
