# Table of Contents
# 00 projects
# 01 unpackaged software
# 02 zsh plugins
# 03 vim plugins


# 00 projects
{{ if .abnormal }}
["Development/github.com/abnormal-security/source"]
  type = "git-repo"
  url = "https://github.com/abnormal-security/source"
{{ end }}


# 01 unpackaged software
[".local/share/git-fuzzy"]
  type = "git-repo"
  url = "https://github.com/bigH/git-fuzzy"
  refreshPeriod = "168h"

# 02 zsh plugins
[".zsh/znap/zsh-snap"]
  type = "archive"
  url = "https://github.com/marlonrichert/zsh-snap/archive/refs/heads/main.zip"
  exact = true
  stripComponents = 1
  refreshPeriod = "168h"

# 03 vim plugins
[".vim/autoload/pathogen.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
  refreshPeriod = "168h"
[".vim/colors/made-of-code.vim"]
  type = "file"
  url = "https://raw.githubusercontent.com/indirect/dotfiles/main/dot_vim/colors/made-of-code.vim"
  refreshPeriod = "168h"
[".vim/pack/plugins/opt/chezmoi.vim"]
  type = "git-repo"
  url = "https://github.com/alker0/chezmoi.vim.git"
  refreshPeriod = "168h"

{{ with $content := include "dot_vim/github_plugins.txt" }}
{{- with $lines := mustRegexSplit "\n+" $content -1 -}}
{{- range $lines -}}
{{- if nospace . -}}
[".vim/pack/chezmoi/start/{{ with mustRegexSplit "/" . 2  }}{{index . 1}}{{end}}"]
  type = "git-repo"
  url = "https://github.com/{{ . }}.git"
  refreshPeriod = "168h"
{{ end -}}
{{- end -}}
{{- end -}}
{{- end -}}